<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect username or password.' => 'Неправильное имя пользователя или пароль.',
    'Create' => 'Создать',
    'Create a group' => 'Создать группу',
    'Create a object' => 'Создать объект',
    'Date' => 'Дата',
    'Date of activity' => 'Дата активности',
    'Delete' => 'Удалить',
    'Event' => 'Событие',
    'Group' => 'Группа',
    'Groups' => 'Группы',
    'Home' => 'Домой',
    'ID' => 'ID',
    'IP' => 'IP',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Object' => 'Объект',
    'Objects' => 'Объекты',
    'Password' => 'Пароль',
    'Please fill out the following fields to login' => 'Пожалуйста, заполните следующие поля для входа',
    'Port' => 'Порт',
    'Port TCP' => 'Порт TCP',
    'Port UDP' => 'Порт UDP',
    'Remember Me' => 'Запомнить меня',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Username' => 'Логин',
    'Is Disable' => 'Отключен',
];
