<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Are you sure you want to clear the history of this object?' => 'Вы уверены, что хотите очистить историю этого объекта?',
    'Are you sure you want to delete this item with all objects?' => 'Вы уверены, что хотите удалить этот элемент вместе со всеми объектами?',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Average RTT' => 'Средний RTT',
    'Clear history' => 'Очистить историю',
    'Create a group' => 'Создать группу',
    'Create a object' => 'Создать объект',
    'Create' => 'Создать',
    'Creating a group' => 'Создание группы',
    'Creating an object' => 'Создание объекта',
    'Date of activity' => 'Дата активности',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Editing a group' => 'Редактирование группы',
    'Editing an object' => 'Редактирование объекта',
    'Editing' => 'Редактирование',
    'Event' => 'Событие',
    'Events' => 'События',
    'Group' => 'Группа',
    'Groups' => 'Группы',
    'Home' => 'Домой',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Неправильное имя пользователя или пароль.',
    'Information' => 'Информация',
    'IP' => 'IP',
    'Is disable' => 'Отключен',
    'Lock date' => 'Дата блокировки',
    'Login' => 'Войти',
    'Logout' => 'Выйти',
    'Note' => 'Заметка',
    'Object' => 'Объект',
    'Objects' => 'Объекты',
    'Password' => 'Пароль',
    'Please fill out the following fields to login' => 'Пожалуйста, заполните следующие поля для входа',
    'Port TCP' => 'Порт TCP',
    'Port UDP' => 'Порт UDP',
    'Remember Me' => 'Запомнить меня',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Update' => 'Редактировать',
    'Username' => 'Логин',
    'View' => 'Просмотр',
];
